#!/bin/bash

LSBIN=/usr/bin/ls
AWKBIN=/usr/bin/awk
CUTBIN=/usr/bin/cut
REVBIN=/usr/bin/rev
DATEBIN=/usr/bin/date
FINDBIN=/usr/bin/find
GREPBIN=/usr/bin/grep
SORTBIN=/usr/bin/sort

function get() {
  local xx=()
  AVOID="deprecated"
  for f in $(${LSBIN} -d */ | ${GREPBIN} -vE ${AVOID}); do
    xx+="${f} "
  done
  xx+=". "
  echo "${xx}"
}

function idx() {
  echo -e "/*${3}*/" > ${1}
  AVOID="_?index.yara?|index_|deprecated"
  if [ "${2}" == "." ]; then
    ${FINDBIN} ${2} -regex ".*\.yara?" | ${GREPBIN} -vE "${AVOID}" | ${SORTBIN} | ${AWKBIN} '{print "include \"" $0 "\""}' >> ${1}
  else
    ${FINDBIN} ${2} -regex ".*\.yara?" | ${GREPBIN} -vE "${AVOID}" | ${SORTBIN} | ${AWKBIN} '{print "include \"./" $0 "\""}' >> ${1}
  fi
}

echo "   **************************"
echo "          Yara-Rules"
echo "   **************************"

for f in $(get)
do
  if [ "${f}" == "." ]; then
    NAME="index.yar"
    echo "[+] Generating index..."
  else
    BASE=$(echo ${f} | ${REVBIN} | ${CUTBIN} -c 2- | ${REVBIN})
    NAME="${BASE}"_index.yar
    echo "[+] Generating ${BASE} index..."
  fi

  idx ${NAME} ${BASE} "\nGenerated by Yara-Rules\nOn $(${DATEBIN} +%d-%m-%Y)\n"
done

