/*
Generated by Yara-Rules
On 22-04-2026
*/
include "./elf/elf-generic.yara"
include "./malware/malware-blackcat.yara"
include "./malware/malware-generic.yara"
include "./malware/malware-merlin-c2.yara"
include "./malware/malware-silver.yara"
include "./malware/malware-xmrig.yara"
include "./packer/packer-generic.yara"
include "./pe/pe-generic.yara"
include "./pe/peid-userdb-rules.yara"
include "./shell/shell-generic.yara"
include "./tools/tools-generic.yara"
include "./website/website-generic.yara"
