/*
Generated by Yara-Rules
On 23-04-2026
*/
include "./elf/elf-generic.yara"
include "./malware/linux-trojan-gafgyt.yara"
include "./malware/linux-trojan-mirai.yara"
include "./malware/malware-blackcat.yara"
include "./malware/malware-generic.yara"
include "./malware/malware-merlin-c2.yara"
include "./malware/malware-silver.yara"
include "./malware/malware-xmrig.yara"
include "./packer/packer-generic.yara"
include "./pe/pe-generic.yara"
include "./pe/peid-userdb-rules.yara"
include "./shell/shell-generic.yara"
include "./tools/tools-blister.yara"
include "./tools/tools-generic.yara"
include "./tools/tools-golang.yara"
include "./tools/tools-keys.yara"
include "./tools/tools-nirsoft.yara"
include "./tools/tools-preload.yara"
include "./website/website-generic.yara"
